# Generated by Django 6.0.5 on 2026-05-19 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('GAMER', 'Gamer'), ('PUBLISHER', 'Publisher'), ('ADMIN', 'Admin')], default='GAMER', max_length=20),
        ),
        migrations.AddField(
            model_name='usergamelist',
            name='data_adicao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergamelist',
            name='estado',
            field=models.CharField(choices=[('QUERO_JOGAR', 'Quero Jogar'), ('A_JOGAR', 'A Jogar'), ('CONCLUIDO', 'Concluído')], default='QUERO_JOGAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='usergamelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usergamelist',
            unique_together={('user', 'game')},
        ),
    ]
