# Generated by Django 6.0.5 on 2026-05-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_game_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='resposta_publisher',
            field=models.TextField(blank=True, null=True),
        ),
    ]
