# Generated by Django 6.0.5 on 2026-05-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
