# Generated by Django 6.0.5 on 2026-05-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_survey_surveyoption_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.surveyoption'),
        ),
    ]
