# Generated by Django 6.0.5 on 2026-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_surveyresponse_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamelist',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
