# Generated by Django 6.0.5 on 2026-05-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usergamelist_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='imagem_principal',
            field=models.ImageField(default='game_defaults/cover.png', upload_to='game_covers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='game_galleries')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.game')),
            ],
        ),
    ]
